setup.py

update pin in setup.py
update pin in setup.py to "eth-ape>=0.1.0a31"
review setup.py

chore: update eth-ape>=0.1.0a31 pin in setup.py

---

ape_etherscan/explorer.py

To prevent from even having to deal with breaking changes from `ethpm-types` v0.1.0b5, just use the native decode method in `ethpm_types.ContractType`

refactor: parse from ContractType object

---

README.md
ape_etherscan/client.py
ape_etherscan/exceptions.py
ape_etherscan/utils.py
setup.py
tests/test_etherscan.py

The base URL for the api client when using Fantom networks was missing the `/api` suffix.
This PR fixes it as well as dusts off the plugin a little bit.
The issue was raised by the community so I addressed it!
I just debugged until I saw what was wrong and then fixed it and included fantom in the tests.
You should now be able to get contract types from Fantom.
Use a script like this and connect to Fantom:
```python
from operator import ne
from ape import networks
import click
def main():
provider = networks.provider
network = provider.network
assert network.ecosystem.name == "fantom", "Must use fantom"
explorer = network.explorer
assert explorer is not None, "Must have explorer (ape-etherscan) installed"
address = "0x30Ac60fcbD79E03d51199BA87111b95C06e1E82F"
contract_type = …
```

fix: correct URL in fantom API client

---

README.md
ape_etherscan/client.py
ape_etherscan/exceptions.py
tests/test_etherscan.py

allow specifying multiple api keys to reduce the chances of hitting rate limits.
split the env var we read by comma and choose a random key from it.
it would be possible to do a round robin key rotation if we read it once and wrap it into `itertools.cycle`, then we can call `next(keys)` every time we need to make a request.
```
export ETHERSCAN_API_KEY=KEY1,KEY2
```

feat: allow specifying multiple api keys

---

.pre-commit-config.yaml
ape_etherscan/explorer.py
setup.py
tests/test_etherscan.py

fix: allow getting contract types for non-checksummed addresses

---

ape_etherscan/__init__.py
ape_etherscan/query.py

Partially a realization that Etherscan already has support for several of the types of queries that are supported in our core data query model, so just enabling support for that
Copy-pasted code from this PR: https://github.com/ApeWorX/ape/pull/1277
Install Etherscan plugin and it works with `account.history` requests

feat: add support for using Etherscan as a Query Engine [APE-636]

---

ape_etherscan/__init__.py
ape_etherscan/client.py
tests/conftest.py
tests/test_etherscan.py

As per https://docs.snowtrace.io/v/fuji-snowtrace, adding the Etherscan/Snowtrace API for Avalanche Fuji testnet in client.py

feat: add Avalanche Fuji testnet support [APE-705]

---

ape_etherscan/client.py

Follow-up of https://github.com/ApeWorX/ape-etherscan/pull/73:
- Add logic to give testnet URL of Snowtrace explorer in case we are using Fuji testnet

feat: add Fuji explorer URL [APE-719]

---

ape_etherscan/verify.py
setup.py
tests/conftest.py
tests/test_etherscan.py

formerly https://github.com/ApeWorX/ape-etherscan/pull/70 but pushed upstream for tests

feat: allow verifying contracts that use libraries [APE-718]

---

ape_etherscan/verify.py
setup.py
tests/conftest.py

updates following https://github.com/ApeWorX/ape-solidity/pull/104
also has everything in https://github.com/ApeWorX/ape-etherscan/pull/89 too so let's merge that first plz
fixed tests, that is all

fix: duplicate libraries key in settings dict

---

.pre-commit-config.yaml
CONTRIBUTING.md
ape_etherscan/client.py
ape_etherscan/explorer.py
ape_etherscan/query.py
setup.py
tests/conftest.py

Fixes: APE-1341
So I am minding my own business, running tests in Ape core and all of a sudden I get random assertions errors in ape-etherscan for now reason... ok.
I really am easily peeved by assertion errors in production code. That should never happen.
So I go and look and comes to find out we are not handling the empty list case at all. So i fix it, and guess what happens? I get something **even more dreadful**
```
RuntimeError: No active exception to reraise
```
what.... why would there ever be an empty raise statement in production code?
So i go and fix that too.
Run this test in ape core:
```sh
pytest tests/functional/test_project.py::test_track_deployment_from_unknown_contract_missing_txn_hash
```

fix: Bug where got assertion error and no-exception to re-raise error [APE-1341]

---

.pre-commit-config.yaml
ape_etherscan/client.py
ape_etherscan/utils.py
ape_etherscan/verify.py
setup.py
tests/conftest.py
tests/test_etherscan.py

requires: https://github.com/ApeWorX/ape-optimism/pull/19

feat: add optimism sepolia testnet [APE-1488]

---

README.md
ape_etherscan/client.py
ape_etherscan/config.py
ape_etherscan/explorer.py
ape_etherscan/query.py
ape_etherscan/types.py
setup.py
tests/_utils.py
tests/conftest.py
tests/test_config.py
tests/test_etherscan.py

Adds support for custom networks.
Depends on https://github.com/ApeWorX/ape/pull/1852
When available, it will read the necessary information from the relevant ecosystem or from configuration.  Example configuration:
```yaml
networks:
custom:
- name: customnetwork
chain_id: 31337
default_provider: geth
geth:
ethereum:
customnetwork:
uri: http://localhost:8545
etherscan:
ethereum:
rate_limit: 15
customnetwork:
uri: https://custom.scan
api_uri: https://api.custom.scan/api
```

feat: adds support for custom networks

---

ape_etherscan/verify.py

looks like we were assuming ape-solidity was installed when we shouldnt be

fix: mistaken import from ape-solidity

---

ape_etherscan/client.py
ape_etherscan/utils.py
tests/conftest.py
tests/test_etherscan.py

Added sepolia support for basescan (goerli is deprecated as of 9th February 2024.)
fixes: #

feat: base sepolia

---

.github/workflows/test.yaml
ape_etherscan/verify.py
tests/conftest.py
tests/test_etherscan.py

related: tests failed, fixed in core: https://github.com/ApeWorX/ape/pull/2022

test: fix issues in tests #127

---

ape_etherscan/utils.py
tests/conftest.py
tests/test_etherscan.py

Add holesky to list of networks.
Etherscan supports this longstanding Ethereum testnet, so it should work fine. See also https://github.com/ApeWorX/ape/issues/1932 for context.
fixes: #
Check where sepolia is listed. Add holesky alongside.

feat: add holesky ethereum network

---

ape_etherscan/verify.py

some of the settings were getting needlessly re-generated because of a fallacy.
also, weird quotes.
also added some of the networks (i am aware of) that support JSON verification, i made sure they work.

fix: verification pointlessly regenerates settings issue

---

README.md
ape_etherscan/client.py
ape_etherscan/utils.py
tests/conftest.py
tests/test_client.py
tests/test_etherscan.py
tests/test_types.py

the pager for account history was broken.
you would get to the end and it would try the next page anyway, causing a 500 error.
also, adds missing docs for using account query history.
Also fixes an issue where result: None would crash the handlers, and you get that sometimes.
also fixes the testnet name and tests for scroll

fix: issue with paging account history

---

ape_etherscan/client.py
ape_etherscan/exceptions.py
ape_etherscan/verify.py
tests/conftest.py
tests/test_etherscan.py

This was causing me to pull my hair out! It turns out that etherscan's single-file verification has no way to indicate that viaIR was used by the compiler. However, the standard json method DOES. I guess that historically, only ethereum supported this method, but now it appears that at least Base/Blast (only one's I've tested so far) do - but in any case, viaIR would ALWAYS cause failure in single-file mode. Now if single file mode is being used, it raises an exception explaining as much, and verifies otherwise.
fixes: #
Verified contracts. What I don't know how to do is create actual tests for this beyond dogfood. To that end, I planned on generating a simple few contracts to deploy across several ecosystems.

fix: viaIR would not verify on etherscan 

---

ape_etherscan/verify.py

- Updated SPDX license identifer for AGPL 3.0 or later, based on allowed list - https://spdx.org/licenses/
- Added "polygon" to list of ecosystems that allow multi-file source verification.
fixes: #

fix: Issue with AGPL3-or-later contract verification on Polygon Amoy

---

.pre-commit-config.yaml
ape_etherscan/__init__.py
ape_etherscan/client.py
ape_etherscan/dependency.py
ape_etherscan/explorer.py
ape_etherscan/verify.py
setup.cfg
setup.py
tests/conftest.py

before:
```
In [1]: %time import ape_etherscan
CPU times: user 987 ms, sys: 140 ms, total: 1.13 s
Wall time: 1.15 s
```
after:
```
In [1]: %time import ape_etherscan
CPU times: user 7.72 ms, sys: 3.29 ms, total: 11 ms
Wall time: 10.7 ms
```

perf: plugin load time

---

.pre-commit-config.yaml
ape_etherscan/__init__.py
setup.py

fix: put back package-level `__all__` (exports`

---

README.md
ape_etherscan/client.py
ape_etherscan/exceptions.py
ape_etherscan/explorer.py
ape_etherscan/query.py
ape_etherscan/utils.py
pyproject.toml
setup.py
tests/_utils.py
tests/conftest.py
tests/test_config.py
tests/test_dependency.py
tests/test_etherscan.py

Implement the API defined here  https://github.com/ApeWorX/ape/pull/2325
and use their provided API for getting the list
use the API they document to get the list
```
ape console --network https://arbitrum-nova.publicnode.com
```
then
```
In [1]: provider.network.explorer
Out[1]: Etherscan(name='etherscan', network=<ethereum:custom chain_id=42170>)
```

feat: switch to V2 API and implement `supported_chain` for broader network support

---

setup.py

fix: pin Ape to version needed for networks feature / v2 api
