.pre-commit-config.yaml, README.md, setup.py
=> chore: prepare for beta

README.md, ape_etherscan/explorer.py, setup.py
=> chore: upgrade to v0.1.0

.pre-commit-config.yaml, ape_etherscan/__init__.py, ape_etherscan/client.py, ape_etherscan/exceptions.py, ape_etherscan/explorer.py, setup.py, tests/test_etherscan.py
=> feat: fantom support

ape_etherscan/__init__.py, ape_etherscan/explorer.py
Added support for handling forked networks
fixes: #19
=> fix: add support for forked networks

.pre-commit-config.yaml, pyproject.toml, setup.py
=> chore: upgrade lint dependencies

tests/test_etherscan.py
add tests for fork support
`-fork` str work
Get an account transaction using a forked network
=> test: add tests for fork networks

.pre-commit-config.yaml, README.md, setup.py
Update eth-ape version 💁🏽‍♀️💕🦍
fixes: #
=> chore: update eth-ape base version

ape_etherscan/__init__.py, ape_etherscan/client.py
Added arbitrum networks.
Added arbiscan uris.
=> feat: add arbitrum network and uris

README.md, ape_etherscan/client.py, ape_etherscan/exceptions.py, tests/test_etherscan.py
=> feat: allow specifying multiple api keys (#32)

README.md, ape_etherscan/__init__.py, ape_etherscan/client.py, ape_etherscan/utils.py, setup.py, tests/test_etherscan.py
Completes the work done in https://github.com/ApeWorX/ape-etherscan/pull/29
Thank you @pandadefi for getting it started! I was having issues with it along with wanting to diagnose the black error, add tests, and docs.  I hope that is ok!
* Merge work done by @pandadefi
* Run black (had to do with no trailing comma, the trailing comma helps it maintain its compose else it gets pushed to a single line. The others were multiline probably so we can tell all the networks we support really easily in the code).
* Fix bug where was using wrong API URL
* Add tests (had to comment some out because they require a provider it seems... weird. Need Alchemy for me.)
* Append ecosystem to list in README
Let me know if it works!
=> feat: optimism support

.github/workflows/test.yaml, README.md, ape_etherscan/__init__.py, ape_etherscan/client.py, pyproject.toml, setup.py, tests/conftest.py, tests/test_etherscan.py
=> fix: remove outdated testnets

README.md, ape_etherscan/__init__.py, ape_etherscan/client.py, ape_etherscan/utils.py, tests/conftest.py, tests/test_etherscan.py
Added support for Avalanche. Additionally fixed a few hyperlinks in the README.
=> feat: Avalanche support + fix hyperlinks in README

ape_etherscan/verify.py, tests/conftest.py
=> fix: license bug

README.md, ape_etherscan/__init__.py, ape_etherscan/client.py, ape_etherscan/utils.py, tests/conftest.py, tests/test_etherscan.py
Adds Bscscan support for BSC Network (Mainnet + Testnet)
fixes: APE-448
=> feat: add bsc support

setup.py
A test is broken, probably due to updates in how we handle the project folder not working well with how we are mocking this functionality. Some updates are needed
=> test: add bsc plugin

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/work-item.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/codeql.yml, .github/workflows/commit.yaml, .github/workflows/prtitle.yaml, .github/workflows/publish.yaml, .github/workflows/stale-prs.yml, .github/workflows/test.yaml, .gitignore, .mdformat.toml, .pre-commit-config.yaml, README.md, ape_etherscan/client.py, pyproject.toml, setup.py, tests/conftest.py, tests/test_etherscan.py
=> chore: upgrade to 0.6

ape_etherscan/client.py, ape_etherscan/verify.py
=> feat: use contract file name as source id in request [APE-775]

ape_etherscan/__init__.py, tests/conftest.py, tests/test_etherscan.py
Added the Sepolia testnet to allow the explorer to recognize transactions on the network.
fixes: #
=> feat: Add Sepolia Testnet Support [APE-786]

ape_etherscan/client.py, ape_etherscan/config.py, ape_etherscan/exceptions.py, ape_etherscan/utils.py, tests/conftest.py, tests/test_etherscan.py
add gnosisscan
copied what was done already for other etherscan explorers.
=> feat: add gnosisscan [APE-1025]

.github/workflows/commit.yaml, .github/workflows/prtitle.yaml, .github/workflows/publish.yaml, .github/workflows/test.yaml, .pre-commit-config.yaml, README.md, pyproject.toml, setup.py
=> feat: python 3.11 support [APE-1046]

ape_etherscan/client.py, ape_etherscan/query.py, ape_etherscan/types.py, setup.py
Implements support for https://github.com/ApeWorX/ape/pull/1606 via the Etherscan API
~~- [ ] Documentation has been updated~~
=> feat(query): add support for contract creation data queries [APE-1297]

README.md, ape_etherscan/client.py, ape_etherscan/config.py, ape_etherscan/utils.py, tests/test_etherscan.py
Added blastscan uris/options 
fixes: #
=> feat: add blast network

setup.py, tests/conftest.py
=> fix: add blast to installed test deps

.github/workflows/test.yaml
=> chore: fix macos ci

.github/workflows/test.yaml, .pre-commit-config.yaml, README.md, ape-config.yaml, ape_etherscan/client.py, ape_etherscan/dependency.py, ape_etherscan/explorer.py, ape_etherscan/query.py, ape_etherscan/types.py, ape_etherscan/verify.py, pyproject.toml, setup.py, tests/conftest.py, tests/contracts/subcontracts/foo.sol, tests/dependency/contracts/bar.sol, tests/test_config.py, tests/test_dependency.py, tests/test_etherscan.py
=> feat!: update to 0.8

README.md
Change geth to node to reflect 0.8 changes
fixes: #
=> fix: geth to node

README.md
I was unsure how to do this, went to look it up, couldnt figure it out, so adding this for next time.
=> docs: add nonce example to account query in README

tests/conftest.py
=> test: update test with correct data

ape_etherscan/client.py, tests/conftest.py
As per the documentation, the Polygon Amoy endpoint is incorrect
https://docs.polygonscan.com/getting-started/endpoint-urls
=> fix: update Polygon Amoy api endpoint

ape_etherscan/query.py, ape_etherscan/types.py, tests/conftest.py, tests/test_query.py
pushing https://github.com/ApeWorX/ape-etherscan/pull/124 upstream so tests can run
=> feat: contract creation query update

pyproject.toml, tests/conftest.py, tests/test_etherscan.py, tests/test_query.py
The tests were using old Ape internal API, so had to make some fixes
~~- [ ] New test cases have been added and are passing~~
~~- [ ] Documentation has been updated~~
=> test: make fixes for internal api changes
